"""initial

Revision ID: 8a1ba649da16
Revises: 
Create Date: 2025-05-08 13:15:32.852891

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a1ba649da16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('metric',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('topic_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('source',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('schedules', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('topic',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('content',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['eventhorizon.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('metricvalue',
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_on', sa.DateTime(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['eventhorizon.metric.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('subscription',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('single_metric_pricing', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['eventhorizon.client.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['eventhorizon.topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('transaction',
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['eventhorizon.metric.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['eventhorizon.subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction', schema='eventhorizon')
    op.drop_table('subscription', schema='eventhorizon')
    op.drop_table('metricvalue', schema='eventhorizon')
    op.drop_table('content', schema='eventhorizon')
    op.drop_table('topic', schema='eventhorizon')
    op.drop_table('source', schema='eventhorizon')
    op.drop_table('metric', schema='eventhorizon')
    op.drop_table('client', schema='eventhorizon')
    # ### end Alembic commands ###
