"""Initial tables

Revision ID: 8d7ad4f50cf8
Revises: 
Create Date: 2025-05-04 20:12:30.637727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7ad4f50cf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['eventhorizon.schedule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['eventhorizon.schedule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('client_topic',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['eventhorizon.client.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['eventhorizon.topic.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'topic_id'),
    schema='eventhorizon'
    )
    op.create_table('information_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('happened_on', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['eventhorizon.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_on', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['eventhorizon.topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eventhorizon'
    )
    op.create_table('information_block_topic',
    sa.Column('information_block_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['information_block_id'], ['eventhorizon.information_block.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['eventhorizon.topic.id'], ),
    sa.PrimaryKeyConstraint('information_block_id', 'topic_id'),
    schema='eventhorizon'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information_block_topic', schema='eventhorizon')
    op.drop_table('metric', schema='eventhorizon')
    op.drop_table('information_block', schema='eventhorizon')
    op.drop_table('client_topic', schema='eventhorizon')
    op.drop_table('topic', schema='eventhorizon')
    op.drop_table('source', schema='eventhorizon')
    op.drop_table('schedule', schema='eventhorizon')
    op.drop_table('client', schema='eventhorizon')
    # ### end Alembic commands ###
